let
    Source = Buxar,
    #"Inserted Merged Column" = Table.AddColumn(Source, "Merged", each Text.Combine({Text.From([Date], "en-IN"), [Project], [Unit]}, " | "), type text),
    #"Merged Queries" = Table.NestedJoin(#"Inserted Merged Column", {"Merged"}, IndexQuery, {"Merged"}, "IndexQuery", JoinKind.LeftOuter),
    #"Expanded IndexQuery" = Table.ExpandTableColumn(#"Merged Queries", "IndexQuery", {"Manpower", "End"}, {"Manpower", "End"}),
    #"Added Custom" = Table.AddColumn(#"Expanded IndexQuery", "Custom", each Table.FirstN(Table.RemoveFirstN([Data],[Manpower]),[End] - [Manpower])),
    #"Removed Columns1" = Table.RemoveColumns(#"Added Custom",{"Data", "Merged", "Manpower", "End"}),
    #"Expanded Custom" = Table.ExpandTableColumn(#"Removed Columns1", "Custom", {"Column1", "Column2", "Column3", "Column4", "Column5", "Column6", "Column7", "Column8", "Column9", "Column10", "Column11", "Column12", "Column13", "Column14", "Column15", "Column16", "Column17", "Column18", "Column19", "Column20", "Column21", "Column22", "Column23", "Column24", "Column25", "Column26", "Column27", "Column28", "Column29", "Column30", "Column31", "Column32", "Column33", "Column34", "Column35", "Column36", "Column37", "Column38", "Column39", "Column40", "Column41", "Column42", "Column43", "Column44", "Column45", "Column46", "Column47", "Column48", "Column49", "Column50", "Column51", "Column52", "Column53", "Column54", "Column55", "Column56", "Column57", "Column58", "Column59", "Column60", "Column61", "Column62", "Column63", "Column64", "Column65", "Column66", "Column67", "Column68", "Column69", "Column70", "Column71", "Column72", "Column73", "Column74", "Column75", "Column76", "Column77", "Column78", "Column79", "Column80", "Column81", "Column82", "Column83", "Column84", "Column85", "Column86", "Column87", "Column88", "Column89", "Column90", "Column91", "Column92", "Column93", "Column94", "Column95", "Column96", "Column97", "Column98", "Column99", "Column100", "Column101", "Column102", "Column103", "Column104", "Column105", "Column106", "Column107", "Column108", "Column109", "Column110", "Column111", "Column112", "Column113", "Column114", "Column115", "Column116", "Column117", "Column118", "Column119", "Column120", "Column121", "Column122", "Column123", "Column124", "Column125", "Column126", "Column127", "Column128", "Column129", "Column130", "Column131", "Column132", "Column133", "Column134", "Column135", "Column136", "Column137", "Column138", "Column139", "Column140", "Column141", "Column142", "Column143", "Column144", "Column145", "Column146", "Column147", "Column148", "Column149", "Column150", "Column151", "Column152", "Column153", "Column154", "Column155", "Column156", "Column157", "Column158", "Column159", "Column160", "Column161", "Column162", "Column163", "Column164", "Column165", "Column166", "Column167", "Column168", "Column169", "Column170", "Column171", "Column172", "Column173", "Column174", "Column175", "Column176", "Column177", "Column178", "Column179", "Column180", "Column181", "Column182", "Column183", "Column184", "Column185", "Column186", "Column187", "Column188", "Column189", "Column190", "Column191", "Column192", "Column193", "Column194", "Column195", "Column196", "Column197", "Column198", "Column199", "Column200", "Column201", "Column202", "Column203", "Column204", "Column205", "Column206", "Column207", "Column208", "Column209", "Column210", "Column211", "Column212", "Column213", "Column214", "Column215", "Column216", "Column217", "Column218", "Column219", "Column220", "Column221", "Column222", "Column223", "Column224", "Column225", "Column226", "Column227", "Column228", "Column229", "Column230", "Column231", "Column232", "Column233", "Column234", "Column235", "Column236", "Column237", "Column238", "Column239", "Column240", "Column241", "Column242", "Column243", "Column244", "Column245", "Column246", "Column247", "Column248", "Column249", "Column250", "Column251", "Column252", "Column253"}, {"Column1", "Column2", "Column3", "Column4", "Column5", "Column6", "Column7", "Column8", "Column9", "Column10", "Column11", "Column12", "Column13", "Column14", "Column15", "Column16", "Column17", "Column18", "Column19", "Column20", "Column21", "Column22", "Column23", "Column24", "Column25", "Column26", "Column27", "Column28", "Column29", "Column30", "Column31", "Column32", "Column33", "Column34", "Column35", "Column36", "Column37", "Column38", "Column39", "Column40", "Column41", "Column42", "Column43", "Column44", "Column45", "Column46", "Column47", "Column48", "Column49", "Column50", "Column51", "Column52", "Column53", "Column54", "Column55", "Column56", "Column57", "Column58", "Column59", "Column60", "Column61", "Column62", "Column63", "Column64", "Column65", "Column66", "Column67", "Column68", "Column69", "Column70", "Column71", "Column72", "Column73", "Column74", "Column75", "Column76", "Column77", "Column78", "Column79", "Column80", "Column81", "Column82", "Column83", "Column84", "Column85", "Column86", "Column87", "Column88", "Column89", "Column90", "Column91", "Column92", "Column93", "Column94", "Column95", "Column96", "Column97", "Column98", "Column99", "Column100", "Column101", "Column102", "Column103", "Column104", "Column105", "Column106", "Column107", "Column108", "Column109", "Column110", "Column111", "Column112", "Column113", "Column114", "Column115", "Column116", "Column117", "Column118", "Column119", "Column120", "Column121", "Column122", "Column123", "Column124", "Column125", "Column126", "Column127", "Column128", "Column129", "Column130", "Column131", "Column132", "Column133", "Column134", "Column135", "Column136", "Column137", "Column138", "Column139", "Column140", "Column141", "Column142", "Column143", "Column144", "Column145", "Column146", "Column147", "Column148", "Column149", "Column150", "Column151", "Column152", "Column153", "Column154", "Column155", "Column156", "Column157", "Column158", "Column159", "Column160", "Column161", "Column162", "Column163", "Column164", "Column165", "Column166", "Column167", "Column168", "Column169", "Column170", "Column171", "Column172", "Column173", "Column174", "Column175", "Column176", "Column177", "Column178", "Column179", "Column180", "Column181", "Column182", "Column183", "Column184", "Column185", "Column186", "Column187", "Column188", "Column189", "Column190", "Column191", "Column192", "Column193", "Column194", "Column195", "Column196", "Column197", "Column198", "Column199", "Column200", "Column201", "Column202", "Column203", "Column204", "Column205", "Column206", "Column207", "Column208", "Column209", "Column210", "Column211", "Column212", "Column213", "Column214", "Column215", "Column216", "Column217", "Column218", "Column219", "Column220", "Column221", "Column222", "Column223", "Column224", "Column225", "Column226", "Column227", "Column228", "Column229", "Column230", "Column231", "Column232", "Column233", "Column234", "Column235", "Column236", "Column237", "Column238", "Column239", "Column240", "Column241", "Column242", "Column243", "Column244", "Column245", "Column246", "Column247", "Column248", "Column249", "Column250", "Column251", "Column252", "Column253"}),
    #"Promoted Headers" = Table.PromoteHeaders(#"Expanded Custom", [PromoteAllScalars=true]),
    #"Renamed Columns2" = Table.RenameColumns(#"Promoted Headers",{{Table.ColumnNames(#"Promoted Headers"){0}, "Date"}, {"Buxar", "Project"}, {"Unit-1", "Unit"}, {Table.ColumnNames(#"Promoted Headers"){5}, "Yesterday"}, {Table.ColumnNames(#"Promoted Headers"){6}, "Today"}, {Table.ColumnNames(#"Promoted Headers"){7}, "Tomorrow"}}),
    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns2",{{"Sr. no.", type text}}),
    #"Filtered Rows1" = Table.SelectRows(#"Changed Type", each not Text.Contains([#"Sr. no."], ":")),
    #"Filtered Rows2" = Table.SelectRows(#"Filtered Rows1", each ([#"Sr. no."] <> "Direct Manpower (A)" and [#"Sr. no."] <> "Sr. no." and [#"Sr. no."] <> "Sr. no." and [#"Sr. no."] <> "Total (In Nos)")),
    // Rplaced null with NA to unpivot the column
    #"Replaced Value" = Table.ReplaceValue(#"Filtered Rows2",null,"NA",Replacer.ReplaceValue,{"Manpower #(lf)(In Nos)"}),
    #"Unpivoted Columns" = Table.UnpivotOtherColumns(#"Replaced Value", {"Date", "Project", "Unit", "Sr. no.", "Yesterday", "Today", "Tomorrow", "Name of Agency"}, "Parameter", "Package-1"),
    #"Inserted Text Between Delimiters" = Table.AddColumn(#"Unpivoted Columns", "UOM", each Text.BetweenDelimiters([Parameter], "(In ", ")"), type text),
    #"Extracted Text Before Delimiter" = Table.TransformColumns(#"Inserted Text Between Delimiters", {{"Parameter", each Text.BeforeDelimiter(_, "("), type text}}),
    #"Cleaned Text" = Table.TransformColumns(#"Extracted Text Before Delimiter",{{"Parameter", Text.Clean, type text}}),
    #"Trimmed Text" = Table.TransformColumns(#"Cleaned Text",{{"Parameter", Text.Trim, type text}}),
    #"Added Conditional Column" = Table.AddColumn(#"Trimmed Text", "Custom", each if [#"Package-1"] = "NA" then [#"Sr. no."] else [#"Package-1"]),
    #"Extracted Text Before Delimiter1" = Table.TransformColumns(#"Added Conditional Column", {{"Custom", each Text.BeforeDelimiter(_, "("), type text}}),
    #"Cleaned Text1" = Table.TransformColumns(#"Extracted Text Before Delimiter1",{{"Custom", Text.Clean, type text}}),
    #"Replaced Value1" = Table.ReplaceValue(#"Cleaned Text1", each [#"Name of Agency"], each if (Text.Contains([#"Name of Agency"],"Today") or [#"Name of Agency"] = null) then "Other Vendors" else [#"Name of Agency"], Replacer.ReplaceValue, {"Name of Agency"}),
    #"Removed Columns2" = Table.RemoveColumns(#"Replaced Value1",{"Package-1", "Sr. no.", "Yesterday", "Tomorrow"}),
    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns2",{{"Custom", "Package_1"}, {"Name of Agency", "Package_2"}, {"Today", "Value"}}),
    #"Reordered Columns" = Table.ReorderColumns(#"Renamed Columns",{"Date", "Project", "Unit", "Package_1", "Package_2", "UOM", "Parameter", "Value"})
in
    #"Reordered Columns"