let
    Source = Ghatampur,
    #"Filtered Rows" = Table.SelectRows(Source, each ([Package_1] = "b) Group Summary Mech,E&I")),
    #"Extracted Text After Delimiter" = Table.TransformColumns(#"Filtered Rows", {{"Package_1", each Text.AfterDelimiter(_, " ", {0, RelativePosition.FromEnd}), type text}}),
    #"Added Custom" = Table.AddColumn(#"Extracted Text After Delimiter", "CleanData", each Table.RemoveLastN(Table.Skip([Sheets],2),21)),
    #"Removed Columns" = Table.RemoveColumns(#"Added Custom",{"Sheets"}),
    ColumnNamesCleanData = Table.ColumnNames(Table.Combine(#"Removed Columns"[CleanData])),
    #"Expanded Custom" = Table.ExpandTableColumn(#"Removed Columns", "CleanData", ColumnNamesCleanData),
    #"Removed Columns1" = Table.RemoveColumns(#"Expanded Custom",{"Column1", "Column2", "Column23", "Column24", "Column25", "Column26", "Column27", "Column28"}),
    #"Transposed Table" = Table.Transpose(#"Removed Columns1"),
    #"Filled Down" = Table.FillDown(#"Transposed Table",{"Column1"}),
    #"Merged Columns" = Table.CombineColumns(Table.TransformColumnTypes(#"Filled Down", {{"Column1", type text}, {"Column2", type text}}, "en-IN"),{"Column1", "Column2"},Combiner.CombineTextByDelimiter(" | ", QuoteStyle.None),"Merged"),
    #"Transposed Table1" = Table.Transpose(#"Merged Columns"),
    #"Promoted Headers" = Table.PromoteHeaders(#"Transposed Table1", [PromoteAllScalars=true]),
    ColumnNames = Table.FromList(Table.ColumnNames(#"Promoted Headers"), Splitter.SplitByNothing(), null, null, ExtraValues.Error),
    #"Renamed Columns3" = Table.RenameColumns(#"Promoted Headers",{{ColumnNames{0}[Column1], "Date"}, {"Ghatampur | Ghatampur", "Project"}, {"Mech,E&I | Mech,E&I", "Package_1"}, {"Mech,E&I | Sub Group Description ", "Package"}, {"Mech,E&I | UOM", "UOM"}}),
    #"Added Conditional Column" = Table.AddColumn(#"Renamed Columns3", "Package_2", each if [UOM] = null then [Package] else null),
    #"Filled Up" = Table.FillUp(#"Added Conditional Column",{"Package_2"}),
    #"Extracted Text Before Delimiter" = Table.TransformColumns(#"Filled Up", {{"Package_2", each Text.BeforeDelimiter(_, " ("), type text}}),
    #"Filtered Rows2" = Table.SelectRows(#"Extracted Text Before Delimiter", each ([UOM] <> null and [UOM] <> "UOM")),
    #"Renamed Columns" = Table.RenameColumns(#"Filtered Rows2",{{"Package", "Package_3"}}),
    #"Unpivoted Other Columns" = Table.UnpivotOtherColumns(#"Renamed Columns", {"Date", "Project", "Package_1", "Package_2", "Package_3", "UOM"}, "Attribute", "Value"),
    #"Split Column by Delimiter" = Table.SplitColumn(#"Unpivoted Other Columns", "Attribute", Splitter.SplitTextByDelimiter(" | ", QuoteStyle.Csv), {"Unit", "Parameter"}),
    #"Trimmed Text" = Table.TransformColumns(#"Split Column by Delimiter",{{"Parameter", Text.Trim, type text}}),
    #"Cleaned Text" = Table.TransformColumns(#"Trimmed Text",{{"Parameter", Text.Clean, type text}}),
    #"Replaced Errors" = Table.ReplaceErrorValues(#"Cleaned Text", {{"Value", null}}),
    #"Changed Type" = Table.TransformColumnTypes(#"Replaced Errors",{{"Value", type number}, {"Date", type date}, {"Project", type text}, {"Package_1", type text}, {"Package_3", type text}, {"UOM", type text}}),
    #"Pivoted Column" = Table.Pivot(#"Changed Type", List.Distinct(#"Changed Type"[Parameter]), "Parameter", "Value", List.Sum),
    #"Renamed Columns1" = Table.RenameColumns(#"Pivoted Column",{{"Monthly Target", "Target FTM"}, {"Progress Till Last Month", "Completed LM"}, {"Progress ( Day)", "Actual FTD"}, {"Progress (Month)", "Actual FTM"}, {"Progress till Day", "Completed TD"}})
in
    #"Renamed Columns1"