let
    Source = Ghatampur,
    FilteredCivilSummary = Table.SelectRows(Source, each ([Package_1] = "a)-Group summary Civil")),
    #"Extracted Text After Delimiter" = Table.TransformColumns(FilteredCivilSummary, {{"Package_1", each Text.AfterDelimiter(_, " ", {0, RelativePosition.FromEnd}), type text}}),
    AddedCleanData = Table.AddColumn(#"Extracted Text After Delimiter", "CleanData", each Table.RemoveLastN(Table.RemoveFirstN([Sheets],2),6)),
    RemovedSheets = Table.RemoveColumns(AddedCleanData,{"Sheets"}),
    CleanDataColumnNames = Table.ColumnNames(Table.Combine(RemovedSheets[CleanData])),
    ExpandedClnDataUnit123 = Table.ExpandTableColumn(RemovedSheets, "CleanData", CleanDataColumnNames),
    #"Transposed Table" = Table.Transpose(ExpandedClnDataUnit123),
    #"Filled Down" = Table.FillDown(#"Transposed Table",{"Column1"}),
    #"Merged Columns" = Table.CombineColumns(Table.TransformColumnTypes(#"Filled Down", {{"Column1", type text}, {"Column2", type text}}, "en-IN"),{"Column1", "Column2"},Combiner.CombineTextByDelimiter(" | ", QuoteStyle.None),"Merged"),
    #"Transposed Table1" = Table.Transpose(#"Merged Columns"),
    #"Removed Columns1" = Table.RemoveColumns(#"Transposed Table1",{"Column4", "Column26", "Column27", "Column28", "Column29", "Column30", "Column31", "Column32", "Column33", "Column34", "Column35"}),
    #"Promoted Headers" = Table.PromoteHeaders(#"Removed Columns1", [PromoteAllScalars=true]),
    ColumnNames = Table.FromList(Table.ColumnNames(#"Promoted Headers")),
    #"Renamed Columns" = Table.RenameColumns(#"Promoted Headers",{{ColumnNames{0}[Column1], "Date"}, {"Ghatampur | Ghatampur", "Project"}, {"Civil | Sub Group", "Index"}, {"Civil | UOM", "UOM"}, {"Civil | Civil", "Package_1"}, {"Civil | Sub Group Description", "Package"}}),
    #"Added Conditional Column" = Table.AddColumn(#"Renamed Columns", "Package_2", each if [UOM] = null then [Package] else null),
    #"Filled Up" = Table.FillUp(#"Added Conditional Column",{"Package_2"}),
    #"Extracted Text Before Delimiter" = Table.TransformColumns(#"Filled Up", {{"Package_2", each Text.BeforeDelimiter(_, " ("), type text}}),
    #"Filtered Rows" = Table.SelectRows(#"Extracted Text Before Delimiter", each ([Index] <> null and [Index] <> "Sub Group")),
    #"Removed Columns" = Table.RemoveColumns(#"Filtered Rows",{"Index"}),
    #"Unpivoted Other Columns" = Table.UnpivotOtherColumns(#"Removed Columns", {"Date", "Project", "Package_1", "Package_2", "Package", "UOM"}, "Attribute", "Value"),
    #"Split Column by Delimiter" = Table.SplitColumn(#"Unpivoted Other Columns", "Attribute", Splitter.SplitTextByDelimiter(" | ", QuoteStyle.Csv), {"Unit", "Parameter"}),
    #"Trimmed Text" = Table.TransformColumns(#"Split Column by Delimiter",{{"Parameter", Text.Trim, type text}}),
    #"Cleaned Text" = Table.TransformColumns(#"Trimmed Text",{{"Parameter", Text.Clean, type text}}),
    #"Replaced Errors" = Table.ReplaceErrorValues(#"Cleaned Text", {{"Value", null}}),
    #"Renamed Columns1" = Table.RenameColumns(#"Replaced Errors",{{"Package", "Package_3"}}),
    #"Reordered Columns" = Table.ReorderColumns(#"Renamed Columns1",{"Date", "Project", "Unit", "Package_1", "Package_2", "Package_3", "UOM", "Parameter", "Value"}),
    #"Pivoted Column" = Table.Pivot(#"Reordered Columns", List.Distinct(#"Reordered Columns"[Parameter]), "Parameter", "Value", List.Sum),
    #"Renamed Columns2" = Table.RenameColumns(#"Pivoted Column",{{"Monthly Target", "Target FTM"}, {"Progress Till Last Month", "Completed LM"}, {"Progress ( Day)", "Actual FTD"}, {"Progress (Month)", "Actual FTM"}, {"Progress till Day", "Completed TD"}}),
    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns2",{{"Date", type date}, {"Project", type text}, {"Unit", type text}, {"Package_1", type text}, {"Package_2", type text}, {"Package_3", type text}, {"UOM", type text}, {"Scope", type number}, {"Target FTM", Int64.Type}, {"Completed LM", type number}, {"Actual FTD", type number}, {"Actual FTM", type number}, {"Completed TD", type number}})
in
    #"Changed Type"