let
    Source = Excel.Workbook(File.Contents("\\mydata01\02.TeamData\14.ProjectControls&CapabilityCenter\02.InternalReporting\2.4 Flash Reports\2.4.0 Database\1. DPR\1. Ghatampur\2022\2022-04\2022-04_Ghatampur_DPR_Database.xlsx"), null, true),
    Ghatampur_Progress_Table = Source{[Item="Ghatampur_Progress",Kind="Table"]}[Data],
    #"Changed Type" = Table.TransformColumnTypes(Ghatampur_Progress_Table,{{"Date", type date}, {"Project_Progress_ID", Int64.Type}, {"Project", type text}, {"Project_ID", Int64.Type}, {"Unit", type text}, {"Project_Progress_Unit_ID", Int64.Type}, {"Package_3", type text}, {"Package_1", type text}, {"Project_Progress_Package_1_ID", Int64.Type}, {"Package_2", type text}, {"Project_Progress_Package_2_ID", Int64.Type}, {"Project_Progress_Package_3_ID", Int64.Type}, {"UOM", type text}, {"Project_Progress_UOM_ID", Int64.Type}, {"Scope", type number}, {"Target FTM", Int64.Type}, {"Completed LM", type number}, {"Actual FTD", Int64.Type}, {"Actual FTM", Int64.Type}, {"Completed TD", type number}})
in
    #"Changed Type"