let
    Source = Excel.Workbook(File.Contents("\\mydata01\02.TeamData\14.ProjectControls&CapabilityCenter\02.InternalReporting\2.4 Flash Reports\2.4.0 Database\4. MPW S-Curves\2. Khurja\2022\2022-02\2022-02 MPW S Curves Khurja.xlsx"), null, true),
    #"Filtered Rows" = Table.SelectRows(Source, each ([Kind] = "Table")),
    #"Removed Other Columns" = Table.SelectColumns(#"Filtered Rows",{"Data"}),
    Data = #"Removed Other Columns"{0}[Data],
    #"Changed Type" = Table.TransformColumnTypes(Data,{{"AuditMonth", type date}, {"Project", type text}, {"Unit", type text}, {"Package", type text}, {"Parameter", type text}, {"01-08-2019", Int64.Type}, {"01-09-2019", Int64.Type}, {"01-10-2019", Int64.Type}, {"01-11-2019", Int64.Type}, {"01-12-2019", Int64.Type}, {"01-01-2020", Int64.Type}, {"01-02-2020", Int64.Type}, {"01-03-2020", Int64.Type}, {"01-04-2020", Int64.Type}, {"01-05-2020", Int64.Type}, {"01-06-2020", Int64.Type}, {"01-07-2020", Int64.Type}, {"01-08-2020", Int64.Type}, {"01-09-2020", Int64.Type}, {"01-10-2020", type number}, {"01-11-2020", type number}, {"01-12-2020", type number}, {"01-01-2021", type number}, {"01-02-2021", type number}, {"01-03-2021", type number}, {"01-04-2021", type number}, {"01-05-2021", type number}, {"01-06-2021", type number}, {"01-07-2021", type number}, {"01-08-2021", type number}, {"01-09-2021", type number}, {"01-10-2021", type number}, {"01-11-2021", type number}, {"01-12-2021", type number}, {"01-01-2022", type number}, {"01-02-2022", type number}, {"01-03-2022", type number}, {"01-04-2022", type number}, {"01-05-2022", type number}, {"01-06-2022", type number}, {"01-07-2022", type number}, {"01-08-2022", type number}, {"01-09-2022", type number}, {"01-10-2022", type number}, {"01-11-2022", type number}, {"01-12-2022", type number}, {"01-01-2023", type number}, {"01-02-2023", type number}, {"01-03-2023", type number}, {"01-04-2023", type number}, {"01-05-2023", type number}, {"01-06-2023", type number}, {"01-07-2023", type number}, {"01-08-2023", type number}, {"01-09-2023", type number}, {"01-10-2023", type number}, {"01-11-2023", type number}, {"01-12-2023", type number}, {"01-01-2024", type number}, {"01-02-2024", type number}, {"01-03-2024", type number}, {"01-04-2024", type number}, {"01-05-2024", type number}, {"01-06-2024", type number}, {"01-07-2024", type number}, {"01-08-2024", type number}, {"01-09-2024", type number}}),
    #"Replaced Value" = Table.ReplaceValue(#"Changed Type"," # ","-0",Replacer.ReplaceText,{"Unit"})
in
    #"Replaced Value"